### ISSUE TITLE
Delete that repo.

### ISSUE THREAD

**Issue by itskiru** [jusdepatate/chasse1825mastodon#2]
This repo is perfect for profiling. 

The fact that a member of the fediverse is also a member of 18-25 shows nothing. Mastodon was created to have a certain freedom of expression and this dissociated little by little giants like Twitter, etc... who only delete accounts as they want.

**Comment by jusdepatate** [comment]
non :)

**Comment by JaredLethal** [comment]
1) @itskiru the members listed here are not listed because they are from 18-25 , they are listed because their toots actually were racist, homophobic, transphobic, antisemitic or generally hateful. We don't care they are from 18-25. We only care about their attitude and toots

2) Mastodon wasn't created to have a creatin freedom of expression (which, btw, you seem to have a biased definition of) it was in fact created to have a decentralized alternative, where some tools were available for a safer experience. 

So, no, we're not letting them talking shit and not facing any consequence :)

**Comment by ffffluffy** [comment]
@r33int I haven't checked every profile here, but every one I mentioned have posted hateful content. And every one else on this list that I have checked (~a dozen) have also posted hateful stuff. If you have any request about suppressing an account on this list, please tell us.
